-- MySQL Script generated by MySQL Workbench
-- 11/02/16 16:39:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bancosangre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancosangre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancosangre` DEFAULT CHARACTER SET utf8 ;
USE `bancosangre` ;

-- -----------------------------------------------------
-- Table `bancosangre`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`usuario` (
  `id_usu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni_usu` VARCHAR(45) NULL,
  `apellidopaterno_usu` VARCHAR(45) NULL,
  `apellidomaterno_usu` VARCHAR(45) NULL,
  `primernombre_usu` VARCHAR(45) NULL,
  `segundonombre_usu` VARCHAR(45) NULL,
  `codigo_usu` VARCHAR(45) NULL,
  `clave_usu` VARCHAR(45) NULL,
  `nivel_usu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usu`),
  UNIQUE INDEX `id_usu_UNIQUE` (`id_usu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`bancodesangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`bancodesangre` (
  `id_ban` INT NOT NULL AUTO_INCREMENT,
  `id_usu` INT UNSIGNED NOT NULL,
  `direccion_ban` VARCHAR(45) NULL,
  `tipoinstitucion_ban` VARCHAR(45) NULL,
  `tipobanco_ban` VARCHAR(45) NULL,
  `numerocamas_ban` VARCHAR(45) NULL,
  `responsable_ban` VARCHAR(45) NULL,
  `cargo_ban` VARCHAR(45) NULL,
  `correo_ban` VARCHAR(45) NULL,
  `telefono_ban` VARCHAR(45) NULL,
  `celular_ban` VARCHAR(45) NULL,
  `listaetiquetas_ban` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ban`),
  UNIQUE INDEX `id_ban_UNIQUE` (`id_ban` ASC),
  INDEX `fk_bancodesangre_usuario1_idx` (`id_usu` ASC),
  CONSTRAINT `fk_bancodesangre_usuario1`
    FOREIGN KEY (`id_usu`)
    REFERENCES `bancosangre`.`usuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`postulante` (
  `id_pos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usu` INT UNSIGNED NOT NULL,
  `apellidopaterno_pos` VARCHAR(45) NULL,
  `apellidomaterno_pos` VARCHAR(45) NULL,
  `primernombre_pos` VARCHAR(45) NULL,
  `segundonombre_pos` VARCHAR(45) NULL,
  `sexo_pos` VARCHAR(45) NULL,
  `estadocivil_pos` VARCHAR(45) NULL,
  `dni_pos` VARCHAR(45) NULL,
  `fechanacimiento_pos` DATE NULL,
  `lugarnacimiento_pos` VARCHAR(45) NULL,
  `direccion_pos` VARCHAR(45) NULL,
  `distrito_pos` VARCHAR(45) NULL,
  `telefonofijo_pos` VARCHAR(45) NULL,
  `telefonomovil_pos` VARCHAR(45) NULL,
  `lugarprocedencia_pos` VARCHAR(45) NULL,
  `ocupacion_pos` VARCHAR(45) NULL,
  `centrolaboral_pos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pos`, `id_usu`),
  INDEX `fk_postulante_usuario1_idx` (`id_usu` ASC),
  UNIQUE INDEX `id_pos_UNIQUE` (`id_pos` ASC),
  CONSTRAINT `fk_postulante_usuario1`
    FOREIGN KEY (`id_usu`)
    REFERENCES `bancosangre`.`usuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`examenclinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`examenclinico` (
  `id_exa` INT NOT NULL AUTO_INCREMENT,
  `id_pos` INT UNSIGNED NOT NULL,
  `id_usu` INT UNSIGNED NOT NULL,
  `numero_exa` VARCHAR(45) NULL,
  `tipo_exa` VARCHAR(45) NULL,
  `fecha_exa` DATE NULL,
  `empresa_exa` VARCHAR(45) NULL,
  `gruposanguineo_exa` VARCHAR(45) NULL,
  `factorrh_exa` VARCHAR(45) NULL,
  `peso_exa` VARCHAR(45) NULL,
  `talla_exa` VARCHAR(45) NULL,
  `variantedu_exa` VARCHAR(45) NULL,
  `presionarterial_exa` VARCHAR(45) NULL,
  `accesoovenoso_exa` VARCHAR(45) NULL,
  `observacion_exa` VARCHAR(45) NULL,
  `examinador_exa` VARCHAR(45) NULL,
  `calificador_exa` VARCHAR(45) NULL,
  `situacion_exa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_exa`),
  INDEX `fk_examenclinico_postulante1_idx` (`id_pos` ASC, `id_usu` ASC),
  UNIQUE INDEX `id_exa_UNIQUE` (`id_exa` ASC),
  CONSTRAINT `fk_examenclinico_postulante1`
    FOREIGN KEY (`id_pos` , `id_usu`)
    REFERENCES `bancosangre`.`postulante` (`id_pos` , `id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`prueba` (
  `id_pru` INT NOT NULL AUTO_INCREMENT,
  `id_exa` INT NOT NULL,
  `hematocrito_pru` VARCHAR(45) NULL,
  `hemoglobina_pru` VARCHAR(45) NULL,
  `gruposanguineofactor_pru` VARCHAR(45) NULL,
  `tgp_pru` VARCHAR(45) NULL,
  `antihltv_pru` VARCHAR(45) NULL,
  `vdalrpr_pru` VARCHAR(45) NULL,
  `anticorevhb_pru` VARCHAR(45) NULL,
  `antichagas_pru` VARCHAR(45) NULL,
  `antihtv_pru` VARCHAR(45) NULL,
  `antihcv_pru` VARCHAR(45) NULL,
  `situacion_pru` VARCHAR(45) NULL,
  `fecha_pru` VARCHAR(45) NULL,
  `expediente_pru` VARCHAR(45) NULL,
  `tipo_pru` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pru`),
  UNIQUE INDEX `id_pru_UNIQUE` (`id_pru` ASC),
  INDEX `fk_pruebas_examenclinico1_idx` (`id_exa` ASC),
  CONSTRAINT `fk_pruebas_examenclinico1`
    FOREIGN KEY (`id_exa`)
    REFERENCES `bancosangre`.`examenclinico` (`id_exa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`solicitante` (
  `id_sol` INT NOT NULL AUTO_INCREMENT,
  `id_usu` INT UNSIGNED NOT NULL,
  `dni_sol` VARCHAR(45) NULL,
  `correo_sol` VARCHAR(45) NULL,
  `direccion_sol` VARCHAR(45) NULL,
  `apellidomaterno_sol` VARCHAR(45) NULL,
  `apellidopaterno_sol` VARCHAR(45) NULL,
  `primernombre_sol` VARCHAR(45) NULL,
  `segundonombre_sol` VARCHAR(45) NULL,
  `fechainscripcion_sol` VARCHAR(45) NULL,
  `telefonomovil_sol` VARCHAR(45) NULL,
  `telefonofijo_sol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sol`),
  INDEX `fk_solicitante_usuario1_idx` (`id_usu` ASC),
  UNIQUE INDEX `id_sol_UNIQUE` (`id_sol` ASC),
  CONSTRAINT `fk_solicitante_usuario1`
    FOREIGN KEY (`id_usu`)
    REFERENCES `bancosangre`.`usuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`contactodonante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`contactodonante` (
  `id_con` INT NOT NULL AUTO_INCREMENT,
  `id_pos` INT UNSIGNED NOT NULL,
  `id_sol` INT NOT NULL,
  `correo_con` VARCHAR(45) NULL,
  `ubicacion_con` VARCHAR(45) NULL,
  PRIMARY KEY (`id_con`, `id_sol`),
  INDEX `fk_contactodonante_postulante_idx` (`id_pos` ASC),
  INDEX `fk_contactodonante_solicitante1_idx` (`id_sol` ASC),
  UNIQUE INDEX `id_con_UNIQUE` (`id_con` ASC),
  CONSTRAINT `fk_contactodonante_postulante`
    FOREIGN KEY (`id_pos`)
    REFERENCES `bancosangre`.`postulante` (`id_pos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactodonante_solicitante1`
    FOREIGN KEY (`id_sol`)
    REFERENCES `bancosangre`.`solicitante` (`id_sol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`muestra` (
  `id_mue` INT NOT NULL AUTO_INCREMENT,
  `id_usu` INT NOT NULL,
  `id_pos` INT NOT NULL,
  `id_exa` INT NOT NULL,
  `gruposanuineo_mue` VARCHAR(45) NULL,
  `fechaextraccion_mue` VARCHAR(45) NULL,
  `almecenamiento_mue` VARCHAR(45) NULL,
  `codigosellocalidad_mue` VARCHAR(45) NULL,
  `lotedebolsa_mue` VARCHAR(45) NULL,
  `tipounidad_mue` VARCHAR(45) NULL,
  `diasdevigencia_mue` VARCHAR(45) NULL,
  `condicionesextraccion_mue` VARCHAR(45) NULL,
  `complicacionesextraccion_mue` VARCHAR(45) NULL,
  `extraccioncompleta_mue` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mue`),
  INDEX `fk_muestra_postulante1_idx` (`id_pos` ASC, `id_usu` ASC),
  INDEX `fk_muestra_examenclinico1_idx` (`id_exa` ASC),
  UNIQUE INDEX `id_mue_UNIQUE` (`id_mue` ASC),
  CONSTRAINT `fk_muestra_postulante1`
    FOREIGN KEY (`id_pos` , `id_usu`)
    REFERENCES `bancosangre`.`postulante` (`id_pos` , `id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muestra_examenclinico1`
    FOREIGN KEY (`id_exa`)
    REFERENCES `bancosangre`.`examenclinico` (`id_exa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`receptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`receptor` (
  `id_rec` INT NOT NULL AUTO_INCREMENT,
  `dni_rec` VARCHAR(8) NULL,
  `habitacion_rec` VARCHAR(45) NULL,
  `horatrans_rec` VARCHAR(45) NULL,
  `fechainscripcion_rec` VARCHAR(45) NULL,
  `apellidomaterno_rec` VARCHAR(45) NULL,
  `apellidopaterno_rec` VARCHAR(45) NULL,
  `primernombre_rec` VARCHAR(45) NULL,
  `segundonombre_rec` VARCHAR(45) NULL,
  `telefonomovil_rec` VARCHAR(45) NULL,
  `telefonofijo_rec` VARCHAR(45) NULL,
  `direccion_rec` VARCHAR(45) NULL,
  `correo_rec` VARCHAR(45) NULL,
  `fechaatencion_rec` DATE NULL,
  `receptorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rec`),
  UNIQUE INDEX `id_rec_UNIQUE` (`id_rec` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`orden` (
  `id_ord` INT NOT NULL AUTO_INCREMENT,
  `id_rec` INT NOT NULL,
  `motivo_ord` VARCHAR(45) NULL,
  `tipo_ord` VARCHAR(45) NULL,
  `atencion_ord` VARCHAR(45) NULL,
  `destino_ord` VARCHAR(45) NULL,
  `pruebacomp_ord` VARCHAR(45) NULL,
  `receptor_ord` VARCHAR(100) NULL,
  `grupo_ord` VARCHAR(100) NULL,
  `reaccion_ord` VARCHAR(100) NULL,
  PRIMARY KEY (`id_ord`, `id_rec`),
  UNIQUE INDEX `id_ord_UNIQUE` (`id_ord` ASC),
  INDEX `fk_orden_receptor1_idx` (`id_rec` ASC),
  CONSTRAINT `fk_orden_receptor1`
    FOREIGN KEY (`id_rec`)
    REFERENCES `bancosangre`.`receptor` (`id_rec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosangre`.`transfusion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancosangre`.`transfusion` (
  `id_trans` INT NOT NULL AUTO_INCREMENT,
  `id_ord` INT NOT NULL,
  `id_rec` INT NOT NULL,
  `id_mue` INT NOT NULL,
  `fechaorden_trans` DATE NULL,
  `receptor_trans` VARCHAR(45) NULL,
  `tipatencion_trans` VARCHAR(45) NULL,
  `tipprocedencia_trans` VARCHAR(45) NULL,
  `habitacion_trans` VARCHAR(45) NULL,
  `hemocomponente_trans` VARCHAR(45) NULL,
  `coddon_trans` VARCHAR(45) NULL,
  `estadoorden_trans` VARCHAR(45) NULL,
  `tipoorden_trans` VARCHAR(45) NULL,
  PRIMARY KEY (`id_trans`),
  INDEX `fk_transfusion_orden1_idx` (`id_ord` ASC, `id_rec` ASC),
  UNIQUE INDEX `id_trans_UNIQUE` (`id_trans` ASC),
  INDEX `fk_transfusion_muestra1_idx` (`id_mue` ASC),
  CONSTRAINT `fk_transfusion_orden1`
    FOREIGN KEY (`id_ord` , `id_rec`)
    REFERENCES `bancosangre`.`orden` (`id_ord` , `id_rec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfusion_muestra1`
    FOREIGN KEY (`id_mue`)
    REFERENCES `bancosangre`.`muestra` (`id_mue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
